version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost  # Change to your Docker host IP if needed
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "log-events:1:1"  # Auto-create your test topic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  
  producer:
    build: ./producer
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - rust-grpc

  rust-grpc:
    build: ./rust_grpc_service
    ports:
      - "50051:50051"

  rust_kafka_consumer:
    build: ./rust_kafka_consumer
    depends_on:
      - kafka
    restart: always
