# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/logs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/logs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/logs.proto\x12\x04logs\"-\n\nLogMessage\x12\x0e\n\x06log_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x19\n\x06LogAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32:\n\nLogService\x12,\n\nProcessLog\x12\x10.logs.LogMessage\x1a\x0c.logs.LogAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGMESSAGE']._serialized_start=26
  _globals['_LOGMESSAGE']._serialized_end=71
  _globals['_LOGACK']._serialized_start=73
  _globals['_LOGACK']._serialized_end=98
  _globals['_LOGSERVICE']._serialized_start=100
  _globals['_LOGSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
